name: CI/CD OJS Plugin

on:
  push:
    branches:
      - feat/premium-helper-plugin-abiboulaye
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Lint et Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHP_CodeSniffer (PHP)
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 --extensions=php plugins/generic/premiumSubmissionHelper

      - name: Run ESLint (JS)
        run: npx eslint plugins/generic/premiumSubmissionHelper/js --ext .js

      - name: Run Stylelint (CSS)
        run: npx stylelint "plugins/generic/premiumSubmissionHelper/css/**/*.css"
        

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/feat/premium-helper-plugin-abiboulaye'
    environment: ojs_env
    name: Déploiement

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean old tmp plugin dir
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /var/www/html/ojs/plugins/generic/premiumSubmissionHelper_tmp
            mkdir -p /var/www/html/ojs/plugins/generic/premiumSubmissionHelper_tmp

      - name: Upload plugin files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "plugins/generic/premiumSubmissionHelper/**"
          target: "/var/www/html/ojs/plugins/generic/premiumSubmissionHelper_tmp"
          strip_components: 3

      - name: Activate plugin folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /var/www/html/ojs/plugins/generic/premiumSubmissionHelper
            mv /var/www/html/ojs/plugins/generic/premiumSubmissionHelper_tmp \
               /var/www/html/ojs/plugins/generic/premiumSubmissionHelper
            ls -la /var/www/html/ojs/plugins/generic/premiumSubmissionHelper
