name: OJS Plugin CI

on:
  push:
    branches:
      - feat/premium-helper-plugin-abiboulaye   # Déclenche CI uniquement sur ta branche de dev
  pull_request:                        # Vérifie aussi quand tu crées une PR
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHP_CodeSniffer
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 plugins/generic/premiumSubmissionHelper
