name: Deploy OJS Plugin

on:
  workflow_dispatch:   # Déclenche manuellement depuis GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean old plugin on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /var/www/html/ojs/plugins/generic/premiumSubmissionHelper
            mkdir -p /var/www/html/ojs/plugins/generic/premiumSubmissionHelper

      - name: Upload plugin files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "plugins/generic/premiumSubmissionHelper/*"
          target: "/var/www/html/ojs/plugins/generic/premiumSubmissionHelper"
